### ISSUE TITLE
Request for ground truth cropping information of test images.

### ISSUE THREAD

**Issue by sdonlee88** [yiling-chen/flickr-cropping-dataset#1]
I am a graduated student, studying deep learning networks for image aesthetics.
I downloaded the dataset and check the 'cropping_testing_set.json' and 'cropping_training_set.json'.

I found that there is a cropping information for train dataset but not for test dataset.
So I request the information.
Please answer me, Thanks.

Training
{
        "url":"https://farm5.staticflickr.com/4096/4910188666_04cf9f487d_b.jpg",
        "flickr_photo_id":4910188666,
        "crop":[
            266,
            6,
            757,
            399
        ]
    },

Testing
{
        "url":"https://farm8.staticflickr.com/7218/6931423716_4fb31feac6_c.jpg",
        "flickr_photo_id":6931423716
    },

**Comment by yiling-chen** [comment]
Hi,

Currently, evaluation on the test set is per request.
If you have a cropping method and want to evaluate its accuracy, please send me your results in a text file with each line indicating:
filename x y w h
I should be able to report the scores in the same metric of our paper very quickly.

I will also update the readme to avoid confusion.
Thank you for your interest in this dataset.

**Comment by yiling-chen** [comment]
Hi,
I have released the annotations of test set. Please check out the latest dataset.
