### ISSUE TITLE
Meaning of coordinates

### ISSUE THREAD

**Issue by zijunwei** [yiling-chen/flickr-cropping-dataset#2]
Hi, 
Thanks for sharing the code. 
For the ranking dataset, what does the four numbers mean?
[X1, Y1, X2, Y2] or [X, Y, W, H] or anything else?

**Comment by yiling-chen** [comment]
It means [x y w h] of a crop.

**Comment by zyq950309** [comment]
I found some images of size 2048*1536 has crop coordinates 
130 | 92 | 640 | 480, which is too smal for the image size.Is there a specified scaling relationship to the image size?

**Comment by yiling-chen** [comment]
@zyq950309 
No, there is no scaling needed. Did you try the `cropping_browser.py` script to visualize it and see if that makes sense to you?
