### ISSUE TITLE
About the coordinates

### ISSUE THREAD

**Issue by zyq950309** [yiling-chen/flickr-cropping-dataset#4]
First of all, thanks for your sharing. 
The crop coordinats means [x0,y0,w,h],  but I find sometimes x0+w-1> image.width or y0+h-1>image.height, for example,
{
        "url":"https://farm6.staticflickr.com/5666/21745708903_38eb372588_c.jpg",
        "flickr_photo_id":21745708903,
        "crop":[
            7,
            254,
            793,
            330
        ]
    },
the image size is 799*582, but 254+330-1=583>582
how could I handle this? assign the y1 as h directly?

**Comment by yiling-chen** [comment]
You can do like this.
x1 = min (x0 + w, image_width)
y1 = min(y0 + h, image_height)

**Comment by WujiangXu** [comment]
> You can do like this.
> x1 = min (x0 + w, image_width)
> y1 = min(y0 + h, image_height)

Hello,guys.
I want to ask whether the same format of the sliding_window.json file.

**Comment by yiling-chen** [comment]
> Hello,guys.
> I want to ask whether the same format of the sliding_window.json file.

The sliding windows have the same format.
