### ISSUE TITLE
Error while downloading images

### ISSUE THREAD

**Issue by samyak0210** [yiling-chen/flickr-cropping-dataset#6]
I ran python download_images.py -w 4
Got this error - 
Traceback (most recent call last):
  File "download_images.py", line 51, in <module>
    pool.map(fetch_image, URLs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: cannot identify image file '/tmp/tmpcg2P_9.jpg'

Can you help me with this error.

Thanks!

**Comment by Ddiamondgold** [comment]
I am facing the similar problem.

**Comment by yiling-chen** [comment]
Hi,
I updated the image downloading script and I don't see the reported error on my side anymore. The usage of the script is not changed. Please try again.

**Comment by Ddiamondgold** [comment]
> Hi,
> I updated the image downloading script and I don't see the reported error on my side anymore. The usage of the script is not changed. Please try again.

Thank you very much!
